name: Patch vbmeta for disable verification

on:
  workflow_dispatch:

permissions:
  contents: write
           
jobs:
  patch-recovery-revived:
    runs-on: ubuntu-24.04
    permissions:
      contents: write    
    steps:
      - name: Checkout source
        uses: actions/checkout@main
        with:
          fetch-depth: 1

      - name: Setting Scripts Permission
        run: |    
          chmod +x vbmeta.sh
          chmod +x patch-vbmeta.py

      - name: Running patch-recovery-revived
        run: |
          bash vbmeta.sh
      
      - name: Create release
        uses: ncipollo/release-action@main
        with:
          tag: "${{ github.run_id }}"
          name: Patched-disabled-vbmeta
          artifacts: output/*.img
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
